<!DOCTYPE html><!-- "' --></script></style></noscript></xmp>
<meta charset="utf-8">
<meta name="robots" content="noindex">
<title>Server Error</title>

<style>
	#error-body { background: white; width: 500px; margin: 70px auto; padding: 10px 20px }
	#error-body h1 { font: bold 47px/1.5 sans-serif; background: none; color: #333; margin: .6em 0 }
	#error-body p { font: 21px/1.5 Georgia,serif; background: none; color: #333; margin: 1.5em 0 }
	#error-body small { font-size: 70%; color: gray }
</style>

<script>
    dataLayer = [{'errorCode': 500}];
</script>
<script>(function(w,d,s,l,i){ w[l]=w[l]||[];w[l].push({'gtm.start':
        new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
        j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
        'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
    })(window,document,'script','dataLayer','GTM-WLWCSG');</script>

<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-WLWCSG"
                  height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>

<div id="error-body">
	<h1>Chyba 500</h1>

	<p>Omlouváme se, na serveru nastala chyba a dočasně není možné tuto stránku zobrazit.
        Prosím, zkuste to za chvíli.</p>

	<p><small>error 500</small></p>
</div>
